### ISSUE TITLE
Issue with the dem_parameters script file (Using Sagehen example)

### ISSUE THREAD

**Issue by Bernhard94** [gsflow/gsflow-arcpy#37]
Good day

I'm having some issues running the dem_parameters script file successfully. I am using the Sagehen data as provided. If anyone is able to assist in this matter it would be greatly appreciated. I have attached the codes and errors below. 

Microsoft Windows [Version 10.0.17134.1069]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Admin>cd G:\gsflow-arcpy-master\examples\sagehen\hru_params

C:\Users\Admin>G:

G:\gsflow-arcpy-master\examples\sagehen\hru_params>G:\gsflow-arcpy-master\scripts\dem_parameters.py -i G:\gsflow-arcpy-master\examples\sagehen\hru_params\template_parameters.ini

################################################################################
Run Time Stamp:      2019-10-11 10:33:21.996000
Current Directory:   G:\gsflow-arcpy-master\examples\sagehen\hru_params
Script:              dem_parameters.py

GSFLOW DEM Parameters
  flow_acc_dem_factor was not set in the input file
  Using automatic flow_acc_dem_factor: 1.0

Checking model points shapefile
  Checking model point types

Adding DEM fields if necessary

Projecting DEM raster

Calculating filled DEM raster
Calculating flow direction raster
Calculating flow accumulation raster
Calculating slope raster
  Setting slopes <= 0.01 to 0
Calculating aspect raster
Calculating temperature aspect adjustment raster
Traceback (most recent call last):
  File "G:\gsflow-arcpy-master\scripts\dem_parameters.py", line 699, in <module>
    dem_parameters(config_path=args.ini)
  File "G:\gsflow-arcpy-master\scripts\dem_parameters.py", line 483, in dem_parameters
    dem_aspect_path, temp_adj_remap_path))
  File "C:\Program Files (x86)\ArcGIS\Desktop10.2\arcpy\arcpy\sa\Functions.py", line 5466, in ReclassByASCIIFile
    missing_values)
  File "C:\Program Files (x86)\ArcGIS\Desktop10.2\arcpy\arcpy\sa\Utils.py", line 47, in swapper
    result = wrapper(*args, **kwargs)
  File "C:\Program Files (x86)\ArcGIS\Desktop10.2\arcpy\arcpy\sa\Functions.py", line 5461, in Wrapper
    missing_values)
  File "C:\Program Files (x86)\ArcGIS\Desktop10.2\arcpy\arcpy\geoprocessing\_base.py", line 498, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: ERROR 999999: Error executing function.
Failed to execute (ReclassByASCIIFile).

G:\gsflow-arcpy-master\examples\sagehen\hru_params>

Thank you in advance

**Comment by zzusb** [comment]
Hi @Bernhard94. I have a same question with you. The ReclassByASCIIFile() is a built-in function of Arcgis. More details can be found in this [link](http://desktop.arcgis.com/en/arcmap/10.3/tools/spatial-analyst-toolbox/reclass-by-ascii-file.htm). I suggect you to examine two parameters of ReclassByASCIIFile(xxx, xxxx). Because I find the corresponding relationship of these two parameters maybe inconsist. The first is about aspect, while the second is about temperature. In the remap folder, you can find a "aspect.rmp" file. If you replace the second parameter to aspect.rmp, the script works. But I am not sure this is a valid output.
Good luck:)
